DROP TABLE IF EXISTS dapi;

CREATE TABLE dapi (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  word TEXT UNIQUE NOT NULL,
  definition TEXT NOT NULL
);
